# Change these first
owner: Allovue # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Allovue Login URL
    url: https://loginredirect.allovue.com/login_redirect
    headers:
      - "Content-Type: application/x-www-form-urlencoded; charset=UTF-8"
    body: $LOGIN_CHECK_VALID_POST_DATA
    method: POST

status-website:
  baseUrl: /upptime
  name: Allovue Login Redirect Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
